// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbArancelesPorItems
    {
        public int ArIt_Id { get; set; }
        public string ArIt_Descripcion { get; set; }
        public int? Aran_Id { get; set; }
        public int? Item_Id { get; set; }
        public bool? ArIt_Estado { get; set; }
        public int ArIt_Creacion { get; set; }
        public DateTime ArIt_FechaCreacion { get; set; }
        public int? ArIt_Modifica { get; set; }
        public DateTime? ArIt_FechaModifica { get; set; }
        public double ArIt_Porcentaje { get; set; }

        public virtual tbUsuarios ArIt_CreacionNavigation { get; set; }
        public virtual tbUsuarios ArIt_ModificaNavigation { get; set; }
        public virtual tbAranceles Aran { get; set; }
        public virtual tbItems Item { get; set; }
    }
}