// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbAranceles
    {
        public tbAranceles()
        {
            tbArancelesPorItems = new HashSet<tbArancelesPorItems>();
        }

        public int Aran_Id { get; set; }
        public string Aran_Descripcion { get; set; }
        public bool? Aran_Estado { get; set; }
        public int Aran_Creacion { get; set; }
        public DateTime Aran_FechaCreacion { get; set; }
        public int? Aran_Modifica { get; set; }
        public DateTime? Aran_FechaModifica { get; set; }

        public virtual tbUsuarios Aran_CreacionNavigation { get; set; }
        public virtual tbUsuarios Aran_ModificaNavigation { get; set; }
        public virtual ICollection<tbArancelesPorItems> tbArancelesPorItems { get; set; }
    }
}