// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbBoletinDePago
    {
        public int BoPa_Id { get; set; }
        public int? DeVa_Id { get; set; }
        public string BoPa_Liquidacion { get; set; }
        public string BoPa_NumeroDeclaracion { get; set; }
        public string BoPa_TipoLiquidacion { get; set; }
        public DateTime? BoPa_FechaEmision { get; set; }
        public string BoPa_TipoEstado { get; set; }
        public string BoPa_Observaciones { get; set; }
        public string BoPa_Preimpreso { get; set; }
        public string BoPa_Declarante { get; set; }
        public bool? BoPa_Estado { get; set; }
        public int BoPa_Creacion { get; set; }
        public DateTime BoPa_FechaCreacion { get; set; }
        public int? BoPa_Modifica { get; set; }
        public DateTime? BoPa_FechaModifica { get; set; }

        public virtual tbUsuarios BoPa_CreacionNavigation { get; set; }
        public virtual tbUsuarios BoPa_ModificaNavigation { get; set; }
        public virtual tbDeclaracionDeValor DeVa { get; set; }
    }
}