// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbItems = new HashSet<tbItems>();
        }

        public int Cate_Id { get; set; }
        public string Cate_Descripcion { get; set; }
        public bool? Cate_Estado { get; set; }
        public int Cate_Creacion { get; set; }
        public DateTime Cate_FechaCreacion { get; set; }
        public int? Cate_Modifica { get; set; }
        public DateTime? Cate_FechaModifica { get; set; }

        public virtual tbUsuarios Cate_CreacionNavigation { get; set; }
        public virtual tbUsuarios Cate_ModificaNavigation { get; set; }
        public virtual ICollection<tbItems> tbItems { get; set; }
    }
}