// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbCiudades
    {
        public int Ciud_Id { get; set; }
        public string Ciud_Descripcion { get; set; }
        public int Esta_Id { get; set; }
        public bool? Ciud_Estado { get; set; }
        public int Ciud_Creacion { get; set; }
        public DateTime Ciud_FechaCreacion { get; set; }
        public int? Ciud_Modifica { get; set; }
        public DateTime? Ciud_FechaModifica { get; set; }
        [NotMapped]
        public string Esta_Descripcion { get; set; }
        [NotMapped]
        public string Creacion { get; set; }
        [NotMapped]
        public string Modifica { get; set; }

        public virtual tbUsuarios Ciud_CreacionNavigation { get; set; }
        public virtual tbUsuarios Ciud_ModificaNavigation { get; set; }
        public virtual tbEstados Esta { get; set; }
    }
}