// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbComerciantesIndividuales
    {
        public int CoIn_Id { get; set; }
        public string CoIn_RtnSolicitante { get; set; }
        public int PeNa_Id { get; set; }
        public string CoIn_Aldea { get; set; }
        public string CoIn_CalleYavenida { get; set; }
        public string CoIn_BarrioOcolonia { get; set; }
        public string CoIn_EdificioYnum { get; set; }
        public string CoIn_PuntosDeReferencia { get; set; }
        public string CoIn_Declaracion { get; set; }
        public bool? CoIn_RepresentanteLegal { get; set; }
        public int? EsCi_RepresentanteLegal { get; set; }
        public int? Prof_RepresentanteLegal { get; set; }
        public int? Ciud_RepresentanteLegal { get; set; }

        public int? EsCi_Id { get; set; }
        public int? Prof_Id { get; set; }
        public int? Ciud_Id { get; set; }
        public int? Adua_Id { get; set; }
        public string CoIn_AldeaRepresentanteLegal { get; set; }
        public string CoIn_CalleYavenidaRepresentanteLegal { get; set; }
        public string CoIn_BarrioOcoloniaRepresentanteLegal { get; set; }
        public string CoIn_EdificioYnumRepresentanteLegal { get; set; }
        public string CoIn_PuntosDeReferenciaRepresentanteLegal { get; set; }
        public string CoIn_RtnRepresentanteLegal { get; set; }
        public string CoIn_DNIRepresentanteLegal { get; set; }
        public string CoIn_Rtn { get; set; }
        public string CoIn_DNI { get; set; }

        public string CoIn_Direccion { get; set; }
        public string CoIn_DireccionRepresentanteLegal { get; set; }


        public string CoIn_TelefonoFijo { get; set; }
        public string CoIn_TelefonoCelular { get; set; }

        public string CoIn_Correo { get; set; }
        public string CoIn_CorreoAlternativo { get; set; }

        public string CoIn_RtnUrl { get; set; }
        public string CoIn_RtnRepresentanteLegalUrl { get; set; }
        public string CoIn_DNIUrl { get; set; }
        public string CoIn_DNIRepresentanteLegalUrl { get; set; }

        public string CoIn_DeclaracionUrl { get; set; }


        public bool? CoIn_Estado { get; set; }
        public int CoIn_Creacion { get; set; }
        public DateTime CoIn_FechaCreacion { get; set; }
        public int? CoIn_Modifica { get; set; }
        public DateTime? CoIn_FechaModifica { get; set; }

        public virtual tbCiudades Ciud_RepresentanteLegalNavigation { get; set; }
        public virtual tbUsuarios CoIn_CreacionNavigation { get; set; }
        public virtual tbUsuarios CoIn_ModificaNavigation { get; set; }
        public virtual tbEstadosCiviles EsCi_RepresentanteLegalNavigation { get; set; }
        public virtual tbPersonasNaturales PeNa { get; set; }
        public virtual tbProfesiones Prof_RepresentanteLegalNavigation { get; set; }
    }
}