// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbDeclaracionDeValor
    {
        public tbDeclaracionDeValor()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int DeVa_Id { get; set; }
        public int? DeVa_AduanaIngreso { get; set; }
        public int? DeVa_AduanaDespacho { get; set; }
        public DateTime? DeVa_FechaAceptacion { get; set; }
        public string DeVa_RtnImportador { get; set; }
        public string DeVa_LugarEntrega { get; set; }
        public int? DeVa_PaisEntrega { get; set; }
        public string DeVa_NumeroContrado { get; set; }
        public DateTime? DeVa_FechaContrado { get; set; }
        public int? DeVa_PaisEmbarque { get; set; }
        public int? Deva_LugarEmbarque { get; set; }
        public int? DeVa_PaisExportacion { get; set; }
        public DateTime? DeVa_FechaExportacion { get; set; }
        public string DeVa_Restricciones { get; set; }
        public string DeVa_CondicionContraprestacion { get; set; }
        public decimal? DeVa_MontoReversion { get; set; }
        public string DeVa_TipoVinculacion { get; set; }
        public bool? DeVa_InfluenciaPrecio { get; set; }
        public string DeVa_PagosIndirectosDescuentos { get; set; }
        public string DeVa_CanonDerechosLicencia { get; set; }
        public decimal? DeVa_PrecioFactura { get; set; }
        public decimal? DeVa_PagosIndirectosDescuentosRetroactivos { get; set; }
        public decimal? DeVa_PrecioRealPagado { get; set; }
        public decimal? DeVa_MontoCondicionContraprestacion { get; set; }
        public decimal? DeVa_MontoReversionCasilla { get; set; }
        public decimal? DeVa_GastosComisiones { get; set; }
        public decimal? DeVa_GastosEnvasesEmbalajes { get; set; }
        public decimal? DeVa_ValorMaterialesConsumidos { get; set; }
        public decimal? DeVa_ValorHerramientas { get; set; }
        public decimal? DeVa_ValorMaterialesConsumidos2 { get; set; }
        public decimal? DeVa_ValorIngenieriaCreacion { get; set; }
        public decimal? DeVa_ValorCanoDerechosLicencia { get; set; }
        public decimal? DeVa_GastosTransporteMercaderia { get; set; }
        public decimal? DeVa_GastosCargaDescarga { get; set; }
        public decimal? DeVa_CostosSeguro { get; set; }
        public decimal? DeVa_TotalAjustes { get; set; }
        public decimal? DeVa_GastosConstruccionArmado { get; set; }
        public decimal? DeVa_CostosTransportePosterior { get; set; }
        public decimal? DeVa_DerechosImpuestos { get; set; }
        public decimal? DeVa_MontoIntereses { get; set; }
        public decimal? DeVa_OtrasDeducciones { get; set; }
        public decimal? DeVa_TotalDeducciones { get; set; }
        public decimal? DeVa_ValorAduana { get; set; }
        public bool? DeVa_Estado { get; set; }
        public int DeVa_Creacion { get; set; }
        public DateTime DeVa_FechaCreacion { get; set; }
        public int? DeVa_Modifica { get; set; }
        public DateTime? DeVa_FechaModifica { get; set; }

        public virtual tbUsuarios DeVa_CreacionNavigation { get; set; }
        public virtual tbUsuarios DeVa_ModificaNavigation { get; set; }
        public virtual tbBoletinDePago tbBoletinDePago { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}