// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbEmpleados
    {
        public int Empl_Id { get; set; }
        public string Empl_Rtn { get; set; }
        public string Empl_PrimerNombre { get; set; }
        public string Empl_PrimerApellido { get; set; }
        public string Empl_Sexo { get; set; }
        public int Usua_Id { get; set; }
        public int EsCi_Id { get; set; }
        public int Empr_Id { get; set; }
        public bool? Empl_Estado { get; set; }
        public int Empl_Creacion { get; set; }
        public DateTime Empl_FechaCreacion { get; set; }
        public int? Empl_Modifica { get; set; }
        public DateTime? Empl_FechaModifica { get; set; }

        public virtual tbUsuarios Empl_CreacionNavigation { get; set; }
        public virtual tbUsuarios Empl_ModificaNavigation { get; set; }
        public virtual tbEmpresas Empr { get; set; }
        public virtual tbEstadosCiviles EsCi { get; set; }
        public virtual tbUsuarios Usua { get; set; }
    }
}