// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbEmpresas
    {
        public tbEmpresas()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int Empr_Id { get; set; }
        public string Empr_Descripcion { get; set; }
        public int? Ciud_Id { get; set; }
        public bool? Empr_Estado { get; set; }
        public int Empr_Creacion { get; set; }
        public DateTime Empr_FechaCreacion { get; set; }
        public int? Empr_Modifica { get; set; }
        public DateTime? Empr_FechaModifica { get; set; }
        [NotMapped]
        public int? Esta_Id { get; set; }
        [NotMapped]
        public string Esta_Descripcion { get; set; }
        [NotMapped]
        public string Ciud_Descripcion { get; set; }

        public virtual tbUsuarios Empr_CreacionNavigation { get; set; }
        public virtual tbUsuarios Empr_ModificaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}