// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbComerciantesIndividualesEsCi = new HashSet<tbComerciantesIndividuales>();
            tbComerciantesIndividualesEsCi_RepresentanteLegalNavigation = new HashSet<tbComerciantesIndividuales>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbPersonasJuridicas = new HashSet<tbPersonasJuridicas>();
            tbPersonasNaturales = new HashSet<tbPersonasNaturales>();
        }

        public int EsCi_Id { get; set; }
        public string EsCi_Descripcion { get; set; }
        public bool? EsCi_Estado { get; set; }
        public int EsCi_Creacion { get; set; }
        public DateTime EsCi_FechaCreacion { get; set; }
        public int? EsCi_Modifica { get; set; }
        public DateTime? EsCi_FechaModifica { get; set; }

        public virtual tbUsuarios EsCi_CreacionNavigation { get; set; }
        public virtual tbUsuarios EsCi_ModificaNavigation { get; set; }
        public virtual ICollection<tbComerciantesIndividuales> tbComerciantesIndividualesEsCi { get; set; }
        public virtual ICollection<tbComerciantesIndividuales> tbComerciantesIndividualesEsCi_RepresentanteLegalNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbPersonasJuridicas> tbPersonasJuridicas { get; set; }
        public virtual ICollection<tbPersonasNaturales> tbPersonasNaturales { get; set; }
    }
}