// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbEsquemas
    {
        public tbEsquemas()
        {
            tbPantallas = new HashSet<tbPantallas>();
        }

        public int Esqu_Id { get; set; }
        public string Esqu_Descripcion { get; set; }
        public int Esqu_Creacion { get; set; }
        public DateTime Esqu_FechaCreacion { get; set; }
        public int? Esqu_Modifica { get; set; }
        public DateTime? Esqu_FechaModifica { get; set; }

        public virtual tbUsuarios Esqu_CreacionNavigation { get; set; }
        public virtual tbUsuarios Esqu_ModificaNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallas { get; set; }
    }
}