// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbFacturas
    {
        public tbFacturas()
        {
            tbFacturaDetalle = new HashSet<tbFacturaDetalle>();
        }

        public int Fact_Id { get; set; }
        public string Fact_NumeroFactura { get; set; }
        public DateTime? Fact_Fecha { get; set; }
        public int Deva_Id { get; set; }
        public bool? Fact_Estado { get; set; }
        public int Fact_Creacion { get; set; }
        public DateTime Fact_FechaCreacion { get; set; }
        public int? Fact_Modifica { get; set; }
        public DateTime? Fact_FechaModifica { get; set; }

        public virtual tbDeclaracionDeValor Deva { get; set; }
        public virtual tbUsuarios Fact_CreacionNavigation { get; set; }
        public virtual tbUsuarios Fact_ModificaNavigation { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetalle { get; set; }
    }
}