// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbItems
    {
        public tbItems()
        {
            tbArancelesPorItems = new HashSet<tbArancelesPorItems>();
            tbFacturaDetalle = new HashSet<tbFacturaDetalle>();
        }

        public int Item_Id { get; set; }
        public string Item_Descripcion { get; set; }
        public int? Cate_Id { get; set; }
        public bool? Item_Estado { get; set; }
        public int Item_Creacion { get; set; }
        public DateTime Item_FechaCreacion { get; set; }
        public int? Item_Modifica { get; set; }
        public DateTime? Item_FechaModifica { get; set; }

        public virtual tbCategorias Cate { get; set; }
        public virtual tbUsuarios Item_CreacionNavigation { get; set; }
        public virtual tbUsuarios Item_ModificaNavigation { get; set; }
        public virtual ICollection<tbArancelesPorItems> tbArancelesPorItems { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetalle { get; set; }
    }
}