// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbOficinas
    {
        public tbOficinas()
        {
            tbPersonasNaturales = new HashSet<tbPersonasNaturales>();
        }

        public int Ofic_Id { get; set; }
        public string Ofic_Descripcion { get; set; }
        public int Adua_Id { get; set; }
        public bool? Ofic_Estado { get; set; }
        public int Ofic_Creacion { get; set; }
        public DateTime Ofic_FechaCreacion { get; set; }
        public int? Ofic_Modifica { get; set; }
        public DateTime? Ofic_FechaModifica { get; set; }
        [NotMapped]
        public string Adua_Descripcion { get; set; }
        [NotMapped]
        public string Creacion { get; set; }
        [NotMapped]
        public string Modifica { get; set; }

        public virtual tbAduanas Adua { get; set; }
        public virtual tbUsuarios Ofic_CreacionNavigation { get; set; }
        public virtual tbUsuarios Ofic_ModificaNavigation { get; set; }
        public virtual ICollection<tbPersonasNaturales> tbPersonasNaturales { get; set; }
    }
}