// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbPaises
    {
        public tbPaises()
        {
            tbEstados = new HashSet<tbEstados>();
        }

        public int Pais_Id { get; set; }
        public string Pais_Descripcion { get; set; }
        public bool? Pais_Estado { get; set; }
        public int Pais_Creacion { get; set; }
        public DateTime Pais_FechaCreacion { get; set; }
        public int? Pais_Modifica { get; set; }
        public DateTime? Pais_FechaModifica { get; set; }

        public virtual tbUsuarios Pais_CreacionNavigation { get; set; }
        public virtual tbUsuarios Pais_ModificaNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstados { get; set; }
    }
}