// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbPersonasNaturales
    {
        public tbPersonasNaturales()
        {
            tbComerciantesIndividuales = new HashSet<tbComerciantesIndividuales>();
            tbPersonasJuridicas = new HashSet<tbPersonasJuridicas>();
        }

        public int PeNa_Id { get; set; }
        public string PeNa_Rtn { get; set; }
        public string PeNa_RtnUrlPdf { get; set; }
        public string PeNa_DNI { get; set; }
        public string PeNa_DNIurlPdf { get; set; }
        public string PeNa_NumReciboPublico { get; set; }
        public string PeNa_NumReciboPublicoUrlPdf { get; set; }
        public int? Ofic_Id { get; set; }
        public int EsCi_Id { get; set; }
        public int Prof_Id { get; set; }
        public int Ciud_Id { get; set; }
        public string PeNa_Direccion { get; set; }
        public string PeNa_TelefonoFijo { get; set; }
        public string PeNa_TelefonoCelular { get; set; }
        public string PeNa_Correo { get; set; }
        public string PeNa_CodigoCorreo { get; set; }
        public string PeNa_CorreoAlternativa { get; set; }
        public string PeNa_CodigoCorreoAlternativa { get; set; }
        public bool? PeNa_Estado { get; set; }
        public int PeNa_Creacion { get; set; }
        public DateTime PeNa_FechaCreacion { get; set; }
        public int? PeNa_Modifica { get; set; }
        public DateTime? PeNa_FechaModifica { get; set; }
        public string PeNa_Nombre { get; set; }
        public string PeNa_Apellido { get; set; }
        [NotMapped]
        public int Adua_Id { get; set; }

        public virtual tbCiudades Ciud { get; set; }
        public virtual tbEstadosCiviles EsCi { get; set; }
        public virtual tbOficinas Ofic { get; set; }
        public virtual tbUsuarios PeNa_CreacionNavigation { get; set; }
        public virtual tbUsuarios PeNa_ModificaNavigation { get; set; }
        public virtual tbProfesiones Prof { get; set; }
        public virtual ICollection<tbComerciantesIndividuales> tbComerciantesIndividuales { get; set; }
        public virtual ICollection<tbPersonasJuridicas> tbPersonasJuridicas { get; set; }
    }
}