// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbProfesiones
    {
        public tbProfesiones()
        {
            tbComerciantesIndividuales = new HashSet<tbComerciantesIndividuales>();
            tbPersonasJuridicas = new HashSet<tbPersonasJuridicas>();
            tbPersonasNaturales = new HashSet<tbPersonasNaturales>();
        }

        public int Prof_Id { get; set; }
        public string Prof_Descripcion { get; set; }
        public bool? Prof_Estado { get; set; }
        public int Prof_Creacion { get; set; }
        public DateTime Prof_FechaCreacion { get; set; }
        public int? Prof_Modifica { get; set; }
        public DateTime? Prof_FechaModifica { get; set; }

        public virtual tbUsuarios Prof_CreacionNavigation { get; set; }
        public virtual tbUsuarios Prof_ModificaNavigation { get; set; }
        public virtual ICollection<tbComerciantesIndividuales> tbComerciantesIndividuales { get; set; }
        public virtual ICollection<tbPersonasJuridicas> tbPersonasJuridicas { get; set; }
        public virtual ICollection<tbPersonasNaturales> tbPersonasNaturales { get; set; }
    }
}