// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace sistema_aduana.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsua_CreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsua_ModificaNavigation = new HashSet<tbUsuarios>();
            tbAduanasAdua_CreacionNavigation = new HashSet<tbAduanas>();
            tbAduanasAdua_ModificaNavigation = new HashSet<tbAduanas>();
            tbCiudadesCiud_CreacionNavigation = new HashSet<tbCiudades>();
            tbCiudadesCiud_ModificaNavigation = new HashSet<tbCiudades>();
            tbEmpleadosEmpl_CreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosEmpl_ModificaNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosUsua = new HashSet<tbEmpleados>();
            tbEmpresasEmpr_CreacionNavigation = new HashSet<tbEmpresas>();
            tbEmpresasEmpr_ModificaNavigation = new HashSet<tbEmpresas>();
            tbEstadosCivilesEsCi_CreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEsCi_ModificaNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosEsta_CreacionNavigation = new HashSet<tbEstados>();
            tbEstadosEsta_ModificaNavigation = new HashSet<tbEstados>();
            tbPaisesPais_CreacionNavigation = new HashSet<tbPaises>();
            tbPaisesPais_ModificaNavigation = new HashSet<tbPaises>();
            tbPantallasPant_CreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPant_ModificaNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesPaRo_CreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesPaRo_ModificaNavigation = new HashSet<tbPantallasPorRoles>();
            tbRolesRol_CreacionNavigation = new HashSet<tbRoles>();
            tbRolesRol_ModificaNavigation = new HashSet<tbRoles>();
        }

        public int Usua_Id { get; set; }
        public string Usua_Usuario { get; set; }
        public byte[] Usua_Clave { get; set; }
        public int? Rol_Id { get; set; }
        public bool? Usua_IsAdmin { get; set; }
        public bool? Usua_Estado { get; set; }
        public int Usua_Creacion { get; set; }
        public DateTime Usua_FechaCreacion { get; set; }
        public int? Usua_Modifica { get; set; }
        public DateTime? Usua_FechaModifica { get; set; }
        [NotMapped]
        public string Rol_Descripcion { get; set; }
        [NotMapped]
        public string Creacion { get; set; }
        [NotMapped]
        public string Modifica { get; set; }

        public virtual tbRoles Rol { get; set; }
        public virtual tbUsuarios Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_CreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_ModificaNavigation { get; set; }
        public virtual ICollection<tbAduanas> tbAduanasAdua_CreacionNavigation { get; set; }
        public virtual ICollection<tbAduanas> tbAduanasAdua_ModificaNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_CreacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesCiud_ModificaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmpl_CreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosEmpl_ModificaNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosUsua { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasEmpr_CreacionNavigation { get; set; }
        public virtual ICollection<tbEmpresas> tbEmpresasEmpr_ModificaNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsCi_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsCi_ModificaNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_ModificaNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesPais_CreacionNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesPais_ModificaNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_ModificaNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaRo_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesPaRo_ModificaNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_CreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_ModificaNavigation { get; set; }
    }
}